### ISSUE TITLE
ecma262-compare doesn't have an entry for tc39/ecma262#2440

### ISSUE THREAD

**Issue by rbuckton** [arai-a/ecma262-compare#72]
This may be related to #65, but I wanted to file in issue in case the cause was unrelated.

**Comment by arai-a** [comment]
Thank you for reporting!
It was an error in the build script, that a build failure in other revision results in uncommitted change in working tree, and all subsequent builds fail.

it should be fixed by https://github.com/arai-a/ecma262-compare/commit/67f7ef1dd0dae0dd27fc08a270b8a561b4c39e6b , and the PR should become available within 30 minutes

**Comment by arai-a** [comment]
oh, indeed it's also hitting https://github.com/arai-a/ecma262-compare/issues/65.
will try reducing the history

**Comment by arai-a** [comment]
https://arai-a.github.io/ecma262-compare/?pr=2440
