### ISSUE TITLE
Add option to select release versions?

### ISSUE THREAD

**Issue by yume-chan** [arai-a/ecma262-compare#73]
I want to diff between releases (for example, ES 2020 vs. ES 2021), but I can't find these versions in the Web front-end.

I found commit hashes for each release on https://github.com/tc39/ecma262/releases, for example, ES 2021 is https://github.com/tc39/ecma262/commit/fc85c50181b2b8d7d75f034800528d87fda6b654 committed at 2021-03-09 06:23:39, but I can't find this revision on https://arai-a.github.io/ecma262-compare.

These releases are also git tags so it should be possible to find them in the update script.

**Comment by arai-a** [comment]
Thank you for the suggestion.

There are 2 concerns:

## 1. intermediate commits

Looks like they're in different branches for each release, and those branches have their own history after the base commit
(= https://github.com/tc39/ecma262/commit/f12df860803dd701672a1e6da5c037ff3d4e3710 for es2021).

Is each commit necessary, or is it fine with the topmost commit?

Currently the number of history is limited because of the size limitation of the GitHub Pages (10GB, https://github.com/arai-a/ecma262-compare/issues/65),
and I periodically remove old revisions.
Currently the first commit is from 2020/01/01, and that will change in near future again.
es2019 or older doesn't have their base commit and their ancestor in the history now.
I can add base commit, but not their ancestor, and anyway I'm not sure if it's useful to have non-topmost commits.

## 2. difference of the HTML structure

ecma262-compare uses the rendered result of the spec, and there were some HTML structure changes in past, and I expect it happen in future again,
and I wonder if diff works well between 1 year span.


Anyway, I can add topmost commits for each release to see how it goes.
Give me some time.

**Comment by arai-a** [comment]
Added in https://github.com/arai-a/ecma262-compare/commit/ed87b17e51f69f8436c983a99a81acfe5fdeadd1
will become available shortly.

**Comment by arai-a** [comment]
Currently the topmost commit of each release is added, and their parent is set to the previous release.

**Comment by yume-chan** [comment]
https://github.com/tc39/ecma262/compare/refs/tags/es2021...es2021

I didn't notice there are also branches named after versions, but it looks like the published version (https://262.ecma-international.org/12.0/) is same as the tag "es2021", instead of the branch "es2021". Not sure why there are more commits on branch "es2021".

**Comment by yume-chan** [comment]
About concern 2, I guess these are caused by HTML structure changes?

![image](https://user-images.githubusercontent.com/1330321/134856945-6f787a50-c2f5-4115-ad82-806fc9230297.png)

https://arai-a.github.io/ecma262-compare/?from=156c59d958ae71fb141604211e6f15a9cd5de491&to=41ddcc284ba20945658b96f4c89cc549ab11da30

**Comment by arai-a** [comment]
Thank you for checking!

I'll fix it to use tagged revisions.

about the diff, it seems to be there were 2 spaces and they're modified to 1 space.
what I was wondering was more bigger change, but it seems to be working without much trouble.

**Comment by arai-a** [comment]
Fixed by https://github.com/arai-a/ecma262-compare/commit/0af6d96b78996042a6538858cecb2a859210537e
